### ISSUE TITLE
Misleading "Apache is pervasive" text in README?

### ISSUE THREAD

**Issue by apjanke** [Cybereason/Logout4Shell#1]
Hi there!

Your README currently says:

> Apache is pervasive and comprises nearly a third of all web servers in the world—making this a potentially catastrophic flaw.

This sounds like it is talking about the [Apache HTTP Server](https://httpd.apache.org/). That's a native-code web server program. The vulnerability here is in Apache Log4J, a logging library for Java. These projects are basically unrelated, aside from both being managed under the auspices of the Apache Software Foundation. Log4J is also pervasively used, but for different reasons.

Perhaps this text could be revised?

**Comment by Firesphere** [comment]
Maybe explicitly putting it as "The Apache Software Foundation's products"?

**Comment by apjanke** [comment]
Sounds good to me.

**Comment by Cybereason** [comment]
Merged the changed text. Thanks for clarifying!
