### ISSUE TITLE
Permanent fixing

### ISSUE THREAD

**Issue by S10MC2015** [Cybereason/Logout4Shell#15]
Permanent fixing maybe possible by checking version then rewriting the log4j jar with either forcing disable lookups or killing strlookup or something.

The issue may be some av who check if something is rewriting something it shouldn't be or things checked against checksums. (If these happen I don't particularly know enterprise security for programs and things).

Maybe provide permanent vaccine as an separate file? If file change fails only do temp vaccine?

Maybe make vaccine log more to show maintainers of the affected program that it has been used.

**Comment by SrzStephen** [comment]
> Permanent fixing maybe possible by checking version then rewriting the log4j jar with either forcing disable lookups or killing strlookup or something.

This might interest you
https://github.com/Cybereason/Logout4Shell/pull/8

**Comment by cr-mitmit** [comment]
Thanks to @TudbuT's patch and some changes - we implemented permanent patching.
