### ISSUE TITLE
Error when I execute mvn package.

### ISSUE THREAD

**Issue by R-Gld** [Cybereason/Logout4Shell#23]
Hi, I try to use Logout4Shell but I can't build the project with maven. Any ideas to fix this ?
<img width="562" alt="image" src="https://user-images.githubusercontent.com/29811769/149570167-b3754cad-8582-4533-970f-4b8dc7a7417b.png">

**Comment by R-Gld** [comment]
Fixed with installing the java jdk 8,
`sudo apt install openjdk-8-jre openjdk-8-jdk`
then write in the `~/.mavenrc` file this:
`export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/`

Thanks [StackOverflow](https://stackoverflow.com/a/44439975) !

Have a good day :)

**Comment by cr-mitmit** [comment]
Awesome. Thanks.
