### ISSUE TITLE
Will not patch versions of log4j2 older than 2.10

### ISSUE THREAD

**Issue by alvdavi** [Cybereason/Logout4Shell#3]
Hi, 

The property you are using to disable lookups does not exist for versions older than 2.10:
https://issues.apache.org/jira/browse/LOG4J2-2109

You should look for other alternatives like clearing the `strLookupMap` map (or at least, remove the jndi entry):
https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/Interpolator.java#L56

This map has had other names, in 2.0 it was there, but named `lookups`:
https://github.com/apache/logging-log4j2/blob/log4j-2.0/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/Interpolator.java#L39

**Comment by S10MC2015** [comment]
Maybe a way to detect version of log4j and do whatever it needs depending on version.
2.10 and up --> disablelookups
other --> kill jndi in lookups

**Comment by jameyg42** [comment]
@alvdavi  i was just about to write about strLookupMap myself (and using lookups when strLookupMap doesn't exist)

    LoggerContext ctx = (LoggerContext)LogManager.getContext(false);
    Configuration config = ctx.getConfiguration();
    StrSubstitutor strs = config.getStrSubstitutor();
    Interpolator i = (Interpolator)strs.getVariableResolver();
    i.getStrLookupMap().remove("jndi");

**Comment by Cybereason** [comment]
Pushed a fix that uses the above trick (as a fallback).
Passed all my tests from >= 2.0 to 2.14.1. 
Let me know if you have any issues.
