### ISSUE TITLE
Call out transient nature of fix; changes lost on JVM restart

### ISSUE THREAD

**Issue by dcaslin** [Cybereason/Logout4Shell#7]
Won't an "immunized" server lose this fix on JVM restart? If so, this should be called out loudly and early in the README to avoid giving folks a false sense of security.

**Comment by TudbuT** [comment]
My PR will fix this

**Comment by Cybereason** [comment]
I've clarified the transient nature of the fix. 
I want to gather some community feedback on @TudbuT's fix  - it's very elegant, but there are more risks that the current version takes.
